import org.jetbrains.intellij.platform.gradle.TestFrameworkType

plugins {
    id 'org.jetbrains.intellij.platform' version '2.16.0'
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

group = 'com.github.ttereshchenko'
version = '0.1.0'

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdea('2026.1')
        testFramework(TestFrameworkType.Platform.INSTANCE)
    }
    testImplementation platform('org.junit:junit-bom:6.0.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'junit:junit:4.13.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

intellijPlatform {
    pluginConfiguration {
        name = 'EML Helper'
    }
    publishing {
        token = providers.environmentVariable('PUBLISH_TOKEN')
    }
    signing {
        certificateChain = providers.environmentVariable('CERTIFICATE_CHAIN')
        privateKey = providers.environmentVariable('PRIVATE_KEY')
        password = providers.environmentVariable('PRIVATE_KEY_PASSWORD')
    }
}
